version: "3"
services:
  quanesnet:
    image: nginx
    environment:
      - VIRTUAL_HOST=jsnes.quaren.co.uk
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jsnes.quaren.co.uk
      - LETSENCRYPT_EMAIL=quaren@gmail.com
    volumes:
      - ./:/usr/share/nginx/html:ro

networks:
  default:
    external:
      name: nginx-proxy

